# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-06 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customuser_service_failures'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_activation_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_Activation_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
