# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-06 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180606_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_Activation_timestamp',
        ),
    ]
