# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-06 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_customuser_phone_activation_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_activation_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
