# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-07 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_customuser_phone_activation_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='service_failures',
            field=models.TextField(blank=True, null=True),
        ),
    ]
